//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.07 at 08:51:44 PM CEST 
//


package com.javacook.dddschach.domain;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * Das aktuelle Spielbrett
 * 
 * <p>Java class for AktuellesSpielbrettResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AktuellesSpielbrettResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="spielbrett" type="{http://www.informatikbuero.com/services/dddschach/api/model}Spielbrett"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AktuellesSpielbrettResponse", propOrder = {
    "spielbrett"
})
public class AktuellesSpielbrettResponse implements Serializable
{

    @XmlElement(required = true)
    @NotNull
    @Valid
    protected Spielbrett spielbrett;

    /**
     * Default no-arg constructor
     * 
     */
    public AktuellesSpielbrettResponse() {
        super();
    }

    /**
     * Fully-initialising value constructor
     * 
     */
    public AktuellesSpielbrettResponse(final Spielbrett spielbrett) {
        this.spielbrett = spielbrett;
    }

    /**
     * Gets the value of the spielbrett property.
     * 
     * @return
     *     possible object is
     *     {@link Spielbrett }
     *     
     */
    public Spielbrett getSpielbrett() {
        return spielbrett;
    }

    /**
     * Sets the value of the spielbrett property.
     * 
     * @param value
     *     allowed object is
     *     {@link Spielbrett }
     *     
     */
    public void setSpielbrett(Spielbrett value) {
        this.spielbrett = value;
    }

}
