//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.07 at 08:51:44 PM CEST 
//


package com.javacook.dddschach.domain;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * Fordert das aktuelle Spielbrett an
 * 
 * <p>Java class for AktuellesSpielbrettRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AktuellesSpielbrettRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="clientId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="spielId" type="{http://www.informatikbuero.com/services/dddschach/api/model}SpielId"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AktuellesSpielbrettRequest", propOrder = {
    "clientId",
    "spielId"
})
public class AktuellesSpielbrettRequest implements Serializable {

    protected String clientId;
    @XmlElement(required = true)
    @NotNull
    @Valid
    protected SpielId spielId;

    /**
     * Default no-arg constructor
     * 
     */
    public AktuellesSpielbrettRequest() {
        super();
    }

    /**
     * Fully-initialising value constructor
     * 
     */
    public AktuellesSpielbrettRequest(final String clientId, final SpielId spielId) {
        this.clientId = clientId;
        this.spielId = spielId;
    }

    /**
     * Gets the value of the clientId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * Sets the value of the clientId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientId(String value) {
        this.clientId = value;
    }

    /**
     * Gets the value of the spielId property.
     * 
     * @return
     *     possible object is
     *     {@link SpielId }
     *     
     */
    public SpielId getSpielId() {
        return spielId;
    }

    /**
     * Sets the value of the spielId property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpielId }
     *     
     */
    public void setSpielId(SpielId value) {
        this.spielId = value;
    }


}
