//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.07 at 08:51:44 PM CEST 
//


package com.javacook.dddschach.domain;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FigurenTyp.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FigurenTyp">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="KOENIG"/>
 *     &lt;enumeration value="DAME"/>
 *     &lt;enumeration value="TURM"/>
 *     &lt;enumeration value="LAEUFER"/>
 *     &lt;enumeration value="SPRINGER"/>
 *     &lt;enumeration value="BAUER"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "FigurenTyp")
@XmlEnum
public enum FigurenTyp {

    KOENIG,
    DAME,
    TURM,
    LAEUFER,
    SPRINGER,
    BAUER;

    public String value() {
        return name();
    }

    public static FigurenTyp fromValue(String v) {
        return valueOf(v);
    }

}
