//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.07 at 08:51:44 PM CEST 
//


package com.javacook.dddschach.domain;

import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * Die Id des neu erzeugten Spiels
 * 
 * <p>Java class for FuehreHalbzugAusResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FuehreHalbzugAusResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="halbzugZaehler" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FuehreHalbzugAusResponse", propOrder = {
    "halbzugZaehler"
})
public class FuehreHalbzugAusResponse implements Serializable
{

    @NotNull
    protected int halbzugZaehler;

    /**
     * Default no-arg constructor
     * 
     */
    public FuehreHalbzugAusResponse() {
        super();
    }

    /**
     * Fully-initialising value constructor
     * 
     */
    public FuehreHalbzugAusResponse(final int halbzugZaehler) {
        this.halbzugZaehler = halbzugZaehler;
    }

    /**
     * Gets the value of the halbzugZaehler property.
     * 
     */
    public int getHalbzugZaehler() {
        return halbzugZaehler;
    }

    /**
     * Sets the value of the halbzugZaehler property.
     * 
     */
    public void setHalbzugZaehler(int value) {
        this.halbzugZaehler = value;
    }


}
