//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.07 at 08:51:44 PM CEST 
//


package com.javacook.dddschach.domain;

import javax.validation.Valid;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * Führt einen Halbzug aus
 * 
 * <p>Java class for FuehreHalbzugAusRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FuehreHalbzugAusRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="spielId" type="{http://www.informatikbuero.com/services/dddschach/api/model}SpielId" minOccurs="0"/>
 *         &lt;element name="halbzug" type="{http://www.informatikbuero.com/services/dddschach/api/model}Halbzug" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FuehreHalbzugAusRequest", propOrder = {
    "spielId",
    "halbzug"
})
public class FuehreHalbzugAusRequest implements Serializable {

    @Valid
    protected SpielId spielId;
    @Valid
    protected Halbzug halbzug;

    /**
     * Default no-arg constructor
     * 
     */
    public FuehreHalbzugAusRequest() {
        super();
    }

    /**
     * Fully-initialising value constructor
     * 
     */
    public FuehreHalbzugAusRequest(final SpielId spielId, final Halbzug halbzug) {
        this.spielId = spielId;
        this.halbzug = halbzug;
    }

    /**
     * Gets the value of the spielId property.
     * 
     * @return
     *     possible object is
     *     {@link SpielId }
     *     
     */
    public SpielId getSpielId() {
        return spielId;
    }

    /**
     * Sets the value of the spielId property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpielId }
     *     
     */
    public void setSpielId(SpielId value) {
        this.spielId = value;
    }

    /**
     * Gets the value of the halbzug property.
     * 
     * @return
     *     possible object is
     *     {@link Halbzug }
     *     
     */
    public Halbzug getHalbzug() {
        return halbzug;
    }

    /**
     * Sets the value of the halbzug property.
     * 
     * @param value
     *     allowed object is
     *     {@link Halbzug }
     *     
     */
    public void setHalbzug(Halbzug value) {
        this.halbzug = value;
    }

}
