//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.07 at 08:51:44 PM CEST 
//


package com.javacook.dddschach.domain;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * Halbzug
 * 
 * <p>Java class for Halbzug complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Halbzug">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="von" type="{http://www.informatikbuero.com/services/dddschach/api/model}Position"/>
 *         &lt;element name="nach" type="{http://www.informatikbuero.com/services/dddschach/api/model}Position"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Halbzug", propOrder = {
    "von",
    "nach"
})
public class Halbzug implements Serializable {

    @XmlElement(required = true)
    @NotNull
    @Valid
    protected Position von;
    @XmlElement(required = true)
    @NotNull
    @Valid
    protected Position nach;

    /**
     * Default no-arg constructor
     * 
     */
    public Halbzug() {
        super();
    }

    /**
     * Fully-initialising value constructor
     * 
     */
    public Halbzug(final Position von, final Position nach) {
        this.von = von;
        this.nach = nach;
    }

    /**
     * Gets the value of the von property.
     * 
     * @return
     *     possible object is
     *     {@link Position }
     *     
     */
    public Position getVon() {
        return von;
    }

    /**
     * Sets the value of the von property.
     * 
     * @param value
     *     allowed object is
     *     {@link Position }
     *     
     */
    public void setVon(Position value) {
        this.von = value;
    }

    /**
     * Gets the value of the nach property.
     * 
     * @return
     *     possible object is
     *     {@link Position }
     *     
     */
    public Position getNach() {
        return nach;
    }

    /**
     * Sets the value of the nach property.
     * 
     * @param value
     *     allowed object is
     *     {@link Position }
     *     
     */
    public void setNach(Position value) {
        this.nach = value;
    }

}
