//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.07 at 08:51:44 PM CEST 
//


package com.javacook.dddschach.domain;

import javax.validation.Valid;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 * Die Halbzug-Historie beinhaltet alle bislang ausgeführten Halbzüge
 * 
 * <p>Java class for HalbzugHistorie complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HalbzugHistorie">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="halbzuege" type="{http://www.informatikbuero.com/services/dddschach/api/model}Halbzug" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HalbzugHistorie", propOrder = {
    "halbzuege"
})
public class HalbzugHistorie implements Serializable
{

    @Valid
    protected List<Halbzug> halbzuege;

    /**
     * Default no-arg constructor
     * 
     */
    public HalbzugHistorie() {
        super();
    }

    /**
     * Fully-initialising value constructor
     * 
     */
    public HalbzugHistorie(final List<Halbzug> halbzuege) {
        this.halbzuege = halbzuege;
    }

    /**
     * Gets the value of the halbzuege property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the halbzuege property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHalbzuege().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Halbzug }
     * 
     * 
     */
    public List<Halbzug> getHalbzuege() {
        if (halbzuege == null) {
            halbzuege = new ArrayList<Halbzug>();
        }
        return this.halbzuege;
    }

}
