//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.07 at 08:51:44 PM CEST 
//


package com.javacook.dddschach.domain;

import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * Erzeugt eine neue Spielpartie
 * 
 * <p>Java class for NeuesSpielRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NeuesSpielRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="vermerk" type="{http://www.informatikbuero.com/services/dddschach/api/model}Vermerk" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NeuesSpielRequest", propOrder = {
    "vermerk"
})
public class NeuesSpielRequest implements Serializable
{

    @Size(max = 100)
    protected String vermerk;

    /**
     * Default no-arg constructor
     * 
     */
    public NeuesSpielRequest() {
        super();
    }

    /**
     * Fully-initialising value constructor
     * 
     */
    public NeuesSpielRequest(final String vermerk) {
        this.vermerk = vermerk;
    }

    /**
     * Gets the value of the vermerk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVermerk() {
        return vermerk;
    }

    /**
     * Sets the value of the vermerk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVermerk(String value) {
        this.vermerk = value;
    }


}
