//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.07 at 08:51:44 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.informatikbuero.com/services/com.javacook.dddschach/api/model", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.javacook.dddschach.domain;
