//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.07 at 08:51:44 PM CEST 
//


package com.javacook.dddschach.domain;

import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * Position
 * 
 * <p>Java class for Position complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Position">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="spalte" type="{http://www.informatikbuero.com/services/dddschach/api/model}Spalte"/>
 *         &lt;element name="zeile" type="{http://www.informatikbuero.com/services/dddschach/api/model}Zeile"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Position", propOrder = {
    "spalte",
    "zeile"
})
public class Position implements Serializable
{

    @XmlElement(required = true)
    @NotNull
    protected Spalte spalte;
    @XmlElement(required = true)
    @NotNull
    protected Zeile zeile;

    /**
     * Default no-arg constructor
     * 
     */
    public Position() {
        super();
    }

    /**
     * Fully-initialising value constructor
     * 
     */
    public Position(final Spalte spalte, final Zeile zeile) {
        this.spalte = spalte;
        this.zeile = zeile;
    }

    /**
     * Gets the value of the spalte property.
     * 
     * @return
     *     possible object is
     *     {@link Spalte }
     *     
     */
    public Spalte getSpalte() {
        return spalte;
    }

    /**
     * Sets the value of the spalte property.
     * 
     * @param value
     *     allowed object is
     *     {@link Spalte }
     *     
     */
    public void setSpalte(Spalte value) {
        this.spalte = value;
    }

    /**
     * Gets the value of the zeile property.
     * 
     * @return
     *     possible object is
     *     {@link Zeile }
     *     
     */
    public Zeile getZeile() {
        return zeile;
    }

    /**
     * Sets the value of the zeile property.
     * 
     * @param value
     *     allowed object is
     *     {@link Zeile }
     *     
     */
    public void setZeile(Zeile value) {
        this.zeile = value;
    }

}
