//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.07 at 08:51:44 PM CEST 
//


package com.javacook.dddschach.domain;

import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * Spielfigur
 * 
 * <p>Java class for Spielfigur complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Spielfigur">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="figur" type="{http://www.informatikbuero.com/services/dddschach/api/model}FigurenTyp"/>
 *         &lt;element name="farbe" type="{http://www.informatikbuero.com/services/dddschach/api/model}Farbe"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Spielfigur", propOrder = {
    "figur",
    "farbe"
})
public class Spielfigur implements Serializable
{

    @XmlElement(required = true)
    @NotNull
    protected FigurenTyp figur;
    @XmlElement(required = true)
    @NotNull
    protected Farbe farbe;

    /**
     * Default no-arg constructor
     * 
     */
    public Spielfigur() {
        super();
    }

    /**
     * Fully-initialising value constructor
     * 
     */
    public Spielfigur(final FigurenTyp figur, final Farbe farbe) {
        this.figur = figur;
        this.farbe = farbe;
    }

    /**
     * Gets the value of the figur property.
     * 
     * @return
     *     possible object is
     *     {@link FigurenTyp }
     *     
     */
    public FigurenTyp getFigur() {
        return figur;
    }

    /**
     * Sets the value of the figur property.
     * 
     * @param value
     *     allowed object is
     *     {@link FigurenTyp }
     *     
     */
    public void setFigur(FigurenTyp value) {
        this.figur = value;
    }

    /**
     * Gets the value of the farbe property.
     * 
     * @return
     *     possible object is
     *     {@link Farbe }
     *     
     */
    public Farbe getFarbe() {
        return farbe;
    }

    /**
     * Sets the value of the farbe property.
     * 
     * @param value
     *     allowed object is
     *     {@link Farbe }
     *     
     */
    public void setFarbe(Farbe value) {
        this.farbe = value;
    }

}
