//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.07 at 08:51:44 PM CEST 
//


package com.javacook.dddschach.domain;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 * Spielbrett
 * 
 * <p>Java class for Spielbrett complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Spielbrett">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="spielfelder" type="{http://www.informatikbuero.com/services/dddschach/api/model}Spielfeld" maxOccurs="64"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Spielbrett", propOrder = {
    "spielfelder"
})
public class Spielbrett implements Serializable
{

    @XmlElement(required = true)
    @NotNull
    @Size(min = 1, max = 64)
    @Valid
    protected List<Spielfeld> spielfelder;

    /**
     * Default no-arg constructor
     * 
     */
    public Spielbrett() {
        super();
    }

    /**
     * Fully-initialising value constructor
     * 
     */
    public Spielbrett(final List<Spielfeld> spielfelder) {
        this.spielfelder = spielfelder;
    }

    /**
     * Gets the value of the spielfelder property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the spielfelder property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpielfelder().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Spielfeld }
     * 
     * 
     */
    public List<Spielfeld> getSpielfelder() {
        if (spielfelder == null) {
            spielfelder = new ArrayList<Spielfeld>();
        }
        return this.spielfelder;
    }

}
